### PR TITLE
Preview of scanned image

### PR DESCRIPTION
**Pull request by BugMaker**
Added preview of scanned image, also modified example with custom activity to see it

### CODE REVIEW

**Comment by rkistner** [comment]
Thanks, looks good. Will have a detailed look when I have a chance (in
about 2 weeks).

**Comment by Chesteer89** [comment]
Any ideas how to get rgb bitmap instead of grayscale?

Following code isn't working for me:
```
YuvImage yuvI = new YuvImage(yuvData, ImageFormat.NV21, width, height, null);
	    ByteArrayOutputStream out = new ByteArrayOutputStream();
	    yuvI.compressToJpeg(new Rect(0, 0, width, height), 50, out);
	    byte[] bytes = out.toByteArray();
```

**Comment by rkistner** [comment]
To do that the source YUV data (byte array) will have to be used, since the
LuminanceSource only contains the greyscale data. The rotation will have to
be performed separately on that, but that should be easy with a Bitmap.

**Comment by Chesteer89** [comment]
Oh, right. Done, thanks once again.

**Comment by rkistner** [comment]
I've adapted the code a little to create a colour Bitmap from the source byte array (instead of the PlanarYUVLuminanceSource). The Bitmap is now also created on demand, so there should be no (or little) overhead if it's not used.

Thanks for the work!

**Pull request merged**
