### PR TITLE
Possibility to provide custom layout of a camera scanner

### PR DESCRIPTION
**Pull request by martar**

### CODE REVIEW

**Comment by Antonkog** [comment]
Hi there! Ralf can you please add some opportunity for user to fill barcode in edittext ? It can be some cases when zxing can't read the barcode. So if we will have option to add barcode and confirm it manually it will be perfect.
Thanks in advance!

**Comment by rkistner** [comment]
@Antonkog Adding direct support for EditText is outside the scope of this library. However, from version 3.0 you can create your own Activity with custom layout and logic, which should cover your use case.

I sent you an email with more details.

**Comment by tuandd6585** [comment]
@rkistner How can I custom my own layout and logic inside a fragment ?

**Comment by rkistner** [comment]
@tuandd6585 This example is probably the best starting point: https://github.com/journeyapps/zxing-android-embedded/blob/master/sample/src/main/java/example/zxing/ContinuousCaptureActivity.java

It doesn't use fragments, but that shouldn't make any significant difference.

**Pull request closed without merging**
