### PR TITLE
More custom configs

### PR DESCRIPTION
**Pull request by magnumrocha**
I did some modifications in this library to make this more customisable:

- Added support to user specify a custom layout for the CompoundBarcodeView component.
- Added support to user control the flashlight on CompoundBarcodeView by a custom Activity.
- Added support to user specify custom colors on ViewfinderView component.

Please, check my commits, any feedback will be appreciated...

### CODE REVIEW

**Comment by rkistner** [comment]
Thanks, looks good. I'll go over it in detail soon - may need to make one or two minor changes.

**Comment by rkistner** [comment]
Thanks - merged with some refactoring.

**Comment by magnumrocha** [comment]
Hey @rkistner, thank you for your trust...

So, when the new version of library will be available via gradle ?? I mean, when the new artifact will be released ??

**Comment by rkistner** [comment]
I'll see if I can do that sometime this week.

**Comment by rkistner** [comment]
Released in version 3.0.2.

**Comment by magnumrocha** [comment]
@rkistner cool :thumbsup:

**Pull request merged**
