### PR TITLE
Creating a timeout to finish the scan screen

### PR DESCRIPTION
**Pull request by lucasddaniel**
I'm and my friend djalmaafilho, do this feature, we would like if you can merge this to all.
This is a new feature to set a long timeout to finish the scan intent on handler timeout.

Thanks in advance.

### CODE REVIEW

**Comment by rkistner** [comment]
Thanks, looks good.

For interest's sake, what is your use case for this (why do you need the timeout)?

**Comment by lucasddaniel** [comment]
Hi @rkistner ,
it's a desire of my costumer, because some ice foods can't be recognized, like icecream...
And after this time, my app change the scan to input manually the EAN barcode. :D

**Comment by lucasddaniel** [comment]
Hi @rkistner ,
it's a desire of my costumer, because some ice foods can't be recognized, like icecream...
And after this time, my app change the scan to input manually the EAN barcode. :D

**Comment by lucasddaniel** [comment]
Sorry, I've clicked on wrong button ;)

**Pull request merged**
